//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeconMoon_s_WiiVC_Injector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeconMoon_s_WiiVC_Injector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TOOLDIR {
            get {
                object obj = ResourceManager.GetObject("TOOLDIR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TITLES = https://www.gametdb.com (type: Wii language: ORIG version: 20230426014834)
        ///007E01 = Wii Auto Erase Disc
        ///091E00 = Movie-Ch Install Disc Ver. A
        ///23EE41 = Just Dance 2023 Wii Edition
        ///410E01 = Wii Backup Disc v1.31
        ///413E01 = DiscUpdate Disc
        ///D2AJAF = みんなで冒険!ファミリートレーナー 体験版
        ///D2SE18 = Deca Sports 2 (Demo)
        ///D3DE18 = Deca Sports 3 (Demo)
        ///DASE4Q = Disney Epic Mickey (Demo)
        ///DAUEPZ = Country Dance (Demo)
        ///DAVE01 = Mystery Case Files: The Malgrave Incident (Demo)
        ///DAXE01 = The Legend of Zelda: Skyward Swor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wiitdb {
            get {
                return ResourceManager.GetString("wiitdb", resourceCulture);
            }
        }
    }
}
